### ISSUE TITLE
Request: include python lxml in install (regression?)

### ISSUE THREAD

**Issue by nathanal** [flathub/org.inkscape.Inkscape#93]
This is an optional dependency for Inkscape, but it is used in a lot of extensions. For example, Extensions > Modify Path > Perspective. It would be useful to include.

It is missing in Inkscape 1.1.1 (3bf5ae0d25, 2021-09-20)  Linux Mint 20 .

I'm not sure if this is actually a regression, but it does appear to be installed in the beta branch (Inkscape 1.1-rc (52f87abb86, 2021-05-02) ) and using 1.0.2 (e86c870879, 2021-01-15) (`flatpak update --commit=0ed6f609daa1b304266debbee953c68c007bf357f1b0614348b792ccee8307c0 org.inkscape.Inkscape`)

I'm re-reporting this, it was reported in the Inkscape bugtracker by jordyscript (see https://gitlab.com/inkscape/inkscape/-/issues/2840)

**Comment by hfiguiere** [comment]
lxml was in the GNOME 40 runtime so it was removed. Seems like it needs to be re-added with runtime 41.

Kinda unfortunate.

**Comment by hfiguiere** [comment]
See #94 - this should fix it.

**Comment by nathanal** [comment]
Oh, thanks for the quick response/fix! 

I tried `flatpak install --user https://dl.flathub.org/build-repo/60050/org.inkscape.Inkscape.flatpakref` but the Perspective extension still doesn't recognize lxml. I'm not sure if that's just the nature of the PR though?

**Comment by hfiguiere** [comment]
More context https://gitlab.gnome.org/GNOME/gnome-build-meta/-/issues/380

(I have a fixed fix, the previous was untest as the build take a while)

**Comment by nathanal** [comment]
Ah, confirmed the new PR works!

**Comment by hfiguiere** [comment]
merged. give it a few hours to appear.

**Comment by hfiguiere** [comment]
the update is still building.

**Comment by zeus2021** [comment]
updated, it works. Thanks!
